on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd extensions/prototypes/labgraph_monitor
          yarn
      - name: Run labgraph_monitor tests
        run: |
          cd extensions/prototypes/labgraph_monitor
          yarn test --watchAll=false
          yarn build
